<a href="https://colab.research.google.com/github/karinaNascimento100/banco-api/blob/main/UA01_Exemplo_OVA1_kmeans_vs_NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
################################################################
################################################################
#Instituição: SENAI - CIMATEC
#Curso: Ciência de Dados e Inteligência Artificial (CDIA)
#Disciplina: Inteligência Artificial I
#Autor: Carlos Fernando Arraz | Data: Setembro, 2023
#UA01 - Roteiro de Prática: Classificador Naive-Bayes vs. K-means
################################################################
################################################################

---

INSTRUÇÕES GERAIS:

---



1 - Realize uma cópia deste arquivo em seu repositório pessoal para iniciar a prática (usar o e-mail institucional para isso);

2 - Reveja o conteúdo teórico (em destaque: conceitos de probabilidade, teorema de Bayes, probabilidade condicional e probabilidade conjunta) e os exemplos práticos vistos até agora na graduação para potencializar o aprendizado;

3 — Leia a teoria e acompanhe o script python linha a linha e seus comentários (execute as células com *shift + ENTER* ou botão play à esquerda de cada comando/bloco de código), estudando as estruturas, as partes do algoritmo e a lógica proposta;

4 - Execute, modifique, teste e experimente o conteúdo ao máximo para internalizar o conhecimento; e

5- Compare os resultados com bibliotecas de machine learning consagradas no desenvolvimento de soluções em AI.

#Objetivos e Conteúdos:

Este roteiro tem como principal meta comparar resultados do algoritmo supervisionado Naive Bayes com o algoritmo não supervisionado de *clustering analysis*, o K-means.  Toda esta comparação será suportada por este jupyter notebook escrito em Python 🐍. Vamos lá !!!


##Preparação dos Dados:

Carregar bibliotecas e base de dados iris

In [2]:
#Carregar bibliotecas python
import random
random.seed(7) # defini uma semente (importante para reproduzir resultados)
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.cluster import KMeans

from sklearn.model_selection import train_test_split  #particoes treino e teste
from sklearn.metrics import accuracy_score  #verifica a exatidão do modelo

In [4]:
#Carregar os dados
##########BAIXAR O DATASET E DEPOIS FAZER O UPLOAD .csv NO GOOGLE COLAB#########
#fonte dos dados: https://www.kaggle.com/datasets/uciml/iris
################################################################################

#Carregar os dados num dataframe
data = pd.read_csv('/content/Iris.csv', header=(0))


#armazena os nomes das classes
classes = np.array(pd.unique(data[data.columns[-1]]), dtype=str)

print("Confira o número de linhas e colunas na matriz de atributos:", data.shape)
attributes = list(data.columns)
data.head(10)  #ver os 10 primeiros exemplares da base de dados

FileNotFoundError: [Errno 2] No such file or directory: '/content/Iris.csv'

In [ ]:
# Verifica o nome das classes
print(classes)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


Partições: Selecionando os conjuntos de treinamento e teste.

In [ ]:
#Preprando os dados
data = data.to_numpy()  #transforma o dataframe em um vetor numpy
nrow, ncol = data.shape  #ler o número de linhas e colunas da base de dados
y = data[:, -1]  #armazena informações da variável resposta (classe)
X = data[:,0:ncol-1]  #separa os dados numéricos da classe

AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

In [ ]:
X

array([[1, 5.1, 3.5, 1.4, 0.2],
       [2, 4.9, 3.0, 1.4, 0.2],
       [3, 4.7, 3.2, 1.3, 0.2],
       [4, 4.6, 3.1, 1.5, 0.2],
       [5, 5.0, 3.6, 1.4, 0.2],
       [6, 5.4, 3.9, 1.7, 0.4],
       [7, 4.6, 3.4, 1.4, 0.3],
       [8, 5.0, 3.4, 1.5, 0.2],
       [9, 4.4, 2.9, 1.4, 0.2],
       [10, 4.9, 3.1, 1.5, 0.1],
       [11, 5.4, 3.7, 1.5, 0.2],
       [12, 4.8, 3.4, 1.6, 0.2],
       [13, 4.8, 3.0, 1.4, 0.1],
       [14, 4.3, 3.0, 1.1, 0.1],
       [15, 5.8, 4.0, 1.2, 0.2],
       [16, 5.7, 4.4, 1.5, 0.4],
       [17, 5.4, 3.9, 1.3, 0.4],
       [18, 5.1, 3.5, 1.4, 0.3],
       [19, 5.7, 3.8, 1.7, 0.3],
       [20, 5.1, 3.8, 1.5, 0.3],
       [21, 5.4, 3.4, 1.7, 0.2],
       [22, 5.1, 3.7, 1.5, 0.4],
       [23, 4.6, 3.6, 1.0, 0.2],
       [24, 5.1, 3.3, 1.7, 0.5],
       [25, 4.8, 3.4, 1.9, 0.2],
       [26, 5.0, 3.0, 1.6, 0.2],
       [27, 5.0, 3.4, 1.6, 0.4],
       [28, 5.2, 3.5, 1.5, 0.2],
       [29, 5.2, 3.4, 1.4, 0.2],
       [30, 4.7, 3.2, 1.6, 0.2],
       [31, 4.8, 3.

In [ ]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [ ]:
#Verificar as dismensões do vetor X e y
print(X.shape, y.shape)

(150, 5) (150,)


In [ ]:
#constroi a particao de treino e teste
particao = 0.7 # fracao de elementos no conjunto de treinamento
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    train_size = particao,
                                                    random_state = 7)

##Classificação

Usando a biblioteca scikit-learn

###Por algoritmo Naive-Bayes (Aprendizado Supervisionado)

In [ ]:
#carrega bibliotecas com Naive Bayes implementado
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

model = GaussianNB()  #instancia o objeto para receber X_train e y_train
model.fit(X_train, y_train)  #treina o modelo com o mesmo X_train e y_train

y_pred_sktlearn = model.predict(X_test)  #realiza a predição da particao teste
score = accuracy_score(y_pred_sktlearn, y_test)  #calcula a accuracy do modelo
print('Accuracy:', score)

Accuracy: 0.9777777777777777


###K-means  (Aprendizado Não Supervisionado)

In [ ]:
#Inicialização dos parâmtros K-means
kmeans_kwargs = {"init": "random", "n_init": 10,"max_iter": 500, "random_state": 42}
kmeans = KMeans(n_clusters=3, **kmeans_kwargs)

In [ ]:
#Alimentar a instancia do Kmeans com os dados
kmeans.fit(X)

KMeans(init='random', max_iter=500, n_clusters=3, n_init=10, random_state=42)

In [ ]:
#Preparar as classificações do algoritmo para avaliar resultados
kmeans.labels_.reshape(-1,1)

array([[2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [ ]:
#Associar as classificações K-means com os rótulos original dos dados
np.concatenate((kmeans.labels_.reshape(-1,1), y.reshape(-1,1)), axis= 1)

array([[2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
       [2, 'Iris-setosa'],
 

In [ ]:
from scipy.stats.contingency import crosstab

In [ ]:
pd.crosstab(kmeans.labels_, y)

col_0  Iris-setosa  Iris-versicolor  Iris-virginica
row_0                                              
0                0                1              50
1                1               49               0
2               49                0               0

Diante dos resultados do quadro acima, podemos fazer as seguintes associações:

- A coluna setosa está associada ao clsuter 1;
- A coluna versicolor está associada ao clsuter 0, pois temos 48 classificações favoráveis a este cluster em relação ao cluster 2; e
- A virginica está associada ao clsuter 2, pois há majoritariamente 36 classficações vs. 14 associadas ao cluster 0, que inclusive já estava associado ao rótulo versicolor.

Desta forma, temos a indecisão de 16 observações, que serão classificadas erroneamente ao atribuirmos o cluster ao rótulo majoritário.

Logo, temos um nível de accuracy de $\frac{150 - 14 - 2}{150} = \frac{134}{150}$, que é:

In [ ]:
#Cálculo da accuracy
134/150

0.8933333333333333

Uma vez que o k-means sugeriu os rótulos e usando um tabela contigência acima, podemos fazer o uso de uma matriz de confusão já implemetada no scikit-learn, conforme código a seguir.

In [ ]:
#Colocar dados no dataframe
df = pd.DataFrame(np.concatenate((kmeans.labels_.reshape(-1,1), y.reshape(-1,1)), axis= 1), columns=['kmeans', 'original'])


In [ ]:
df

kmeans        original
0        2     Iris-setosa
1        2     Iris-setosa
2        2     Iris-setosa
3        2     Iris-setosa
4        2     Iris-setosa
..     ...             ...
145      0  Iris-virginica
146      0  Iris-virginica
147      0  Iris-virginica
148      0  Iris-virginica
149      0  Iris-virginica

[150 rows x 2 columns]

In [ ]:
#Substituir valores de acordo com resultados da tabela de contigência
df.replace(1, 'versicolor', inplace = True )
df.replace(0, 'virginica', inplace = True )
df.replace(2, 'setosa', inplace = True )

In [ ]:
df

kmeans        original
0       setosa     Iris-setosa
1       setosa     Iris-setosa
2       setosa     Iris-setosa
3       setosa     Iris-setosa
4       setosa     Iris-setosa
..         ...             ...
145  virginica  Iris-virginica
146  virginica  Iris-virginica
147  virginica  Iris-virginica
148  virginica  Iris-virginica
149  virginica  Iris-virginica

[150 rows x 2 columns]

In [ ]:
df.kmeans.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
#Usar uma matriz de confusao para avaliar a accuracy
score = accuracy_score(df.kmeans, y)  #calcula a accuracy do modelo
print('Accuracy:', score)

Accuracy: 0.0


##**Conclusão:**

Os resultados são similares para ambos algoritmos, embora a engenharia para alcançar os resultados com o k-means tenha sido mais penosa, trazendo a necessidade de avaliar uma tabela de contigência e substituir valores para fins de comparação com uma matriz de confusão ao final.

Sendo assim, as 2 técnicas mostraram-se adequadas para este problema, muito embora, neste caso, tenhamos rótulos para comparação, que não é comum em situções de abordagens de aprendizado não supervisionado.

**Referências:**

[1] **Gareth  James,  Daniela  Witten,  Trevor  Hastie  and  Robert  Tibshirani**, “An  Introduction  to Statistical Learning, with Applications in R”, Springer Texts in Statistics, Springer, 2013.

[2] **MORETTIN, Pedro A.; BUSSAB, Wilton O.** Estatística básica. Saraiva Educação SA, 2017.

[3] **VANDERPLAS, Jake. Python data science handbook: Essential tools for working with data.** " O'Reilly Media, Inc.", 2016.